### Hello Grades, authenticate with Cookie token
GET http://localhost:8080/grades
Cookie: token=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbkBzY2hvb2wuaWUiLCJpYXQiOjE2ODU1NjQwNjUsImV4cCI6MTY4NTU2NDEyNX0.ElVk44nVTdOw_l-OLoYWxzqTHH90EzFHpW8SV8Q_EoB2eWec71JTFuODoe_A-Rhj

### Authenticate
POST http://localhost:8080/api/authenticate
Content-Type: application/json

{
  "email": "admin@school.ie",
  "password": "admin"
}

### Create
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Eliot",
  "lastName": "Test",
  "studentId": "223442",
  "phoneNumber": "123456",
  "email": "e.test@school.ie",
  "password": "secret"
}

### Create
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Tom",
  "lastName": "Trial",
  "studentId": "165685",
  "phoneNumber": "654321",
  "email": "t.trial@school.ie",
  "password": "mystery"
}
